name: calculator-flask-build

on:
  push:
    branches:
      - flask

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        
      - name: Build Docker image
        run: |
          docker build -t calculator .