name: calculator-flask-build

on:
  push:
    branches:
      - flask

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        
      - name: Build Docker image
        run: |
          docker build -t calculator .
      
      - name: Install AWS cli
        run: |
          pip install awscli
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        
      - name: Zip application
        run: |
          zip -r calculator.zip . -x "*.git*" "*.github*" "*.elasticbeanstalk/*" "__pycache__/*"
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws s3 cp calculator.zip s3://elasticbeanstalk-eu-central-1-072929378948/calculator-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version --application-name flask-calculator --version-label ${{ github.sha }} --source-bundle S3Bucket=elasticbeanstalk-eu-central-1-072929378948,S3Key=calculator-${{ github.sha }}.zip
          aws elasticbeanstalk update-environment --environment-name Flask-calculator-env-1 --version-label ${{ github.sha }}